package com.example.demo.controller;


import com.example.demo.entity.Student;
import com.example.demo.model.StudentRequest;
import com.example.demo.repository.StudentRepository;
import com.example.demo.service.StudentService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.*;

import java.util.Collection;
import java.util.List;

@RestController
@RequestMapping("students")
public class StudentController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private StudentRepository studentRepository;

    @Autowired
    private StudentService studentService;

    public StudentController(StudentRepository studentRepository) {
        this.studentRepository = studentRepository;
    }

    //http://localhost:8080/students
    @GetMapping("/all")
    public List <Collection<Student>> getStudents() {
        return studentService.showAllStudents();
    }

    //http://localhost:8080/students//getStudent/62002
    @GetMapping(path = "/getStudent/{stdID}", produces = MediaType.APPLICATION_JSON_VALUE)
    public Student getStudent(@PathVariable Integer stdID) {
        return studentService.showStudent(stdID);
    }

    //http://localhost:8080/addStudent
    @PostMapping("/add")
    public Student addStudent(@RequestBody StudentRequest request) {
        return studentService.saveStudent(request);
    }

    //http://localhost:8080/delete/62006
    @DeleteMapping(path ="/delete/{stdID}")
    public String deleteStudent(@PathVariable Integer stdID) {
        return studentService.deleteStudent(stdID);
    }

    //http://localhost:8080/update/62001/Jundara
    @PutMapping(path ="/update/{stdID}/{fName}")
    public void updateStudentFirstName(@PathVariable Integer stdID,@PathVariable String fName) {
        studentService.updateStudentFirstName(stdID, fName);
    }
}
